### ISSUE TITLE
TOC to lyrics tag

### ISSUE THREAD

**Issue by ragetman** [davidschlachter/itunes-concatenator#15]
Please, make option to add TOC to lyrics tag (like Join Together).

**Comment by davidschlachter** [comment]
I'll do this within a couple weeks.

**Comment by davidschlachter** [comment]
I've just added this to the latest version — use 'Check for updates…' under the Track Concatenator menu to get it.

**Comment by ragetman** [comment]
Many, many thanks!

**Comment by ragetman** [comment]
Many thanks.
I tested new Track Concatenator on Mac OS x 10.9.5 and iTunes 12.2.1.16, filetypes is .m4a and .mp3, option "TOC to lyrics tag" selected.
After the merger is completed the program displays an error message "The concatenated file could not be added to iTunes." and the tag lyrics in the file remains empty (in iTunes > Get Info > Lyrics). The created file is added to the iTunes library.

**Comment by davidschlachter** [comment]
I put out a new update today — I think it'll be more reliable. Just use 'Check for updates…' under the 'Track Concatenator' menu to get it.

In the latest update I've made the error messages more informative. As well, if adding the TOC to the lyrics tag fails, the TOC will be copied to the clipboard so that it could be added manually if required.

Please let me know if the latest version fixes this error for you, and if not, what error message it gives you. Thanks!

**Comment by ragetman** [comment]
The track is created and added to the iTunes library, but an error message: "Track The lyrics tag for the TOC could not be set in iTunes. The error code was -54: iTunes got an error: File permission error. The TOC has been copied to the clipboard instead."
Thanks!

**Comment by davidschlachter** [comment]
I found that adding the TOC fails if the track is accessed too soon after adding it to iTunes. In the latest version, it will wait two seconds, and if not successful, eight seconds more. I've found that this has worked for me — hopefully it fixes it for you too! Just use "Check for updates…" to install the latest version.

**Comment by ragetman** [comment]
I tested last version Track Concatenator - it work, many thanks!
