### ISSUE TITLE
Doesn't work with macOS Catalina Music app

### ISSUE THREAD

**Issue by davidschlachter** [davidschlachter/itunes-concatenator#22]
Investigate if this is possible.

**Comment by fredwaltman** [comment]
I am sure you know this already, but it doesn't work on Catalina. The program launches but there is no way to select tracks (and probably won't save to Music). I recently upgraded to Catalina and went to join the tracks of some music I purchased. I would offer to help but I am strictly a Swift (IOS) guy -- Objective C makes my head hurt :)

**Comment by davidschlachter** [comment]
Thanks for the report. I now have one machine on Catalina and will try to update the program when I get around to it. Track Concatenator is mostly AppleScript in an Objective C wrapper, so it should be possible to detect the OS version and run an appropriate script (since I believe Catalina's Music app still has AppleScript bindings).

**Comment by fredwaltman** [comment]
Doug's scripts work with Music (replacement ones that is, not the original iTunes ones) so you should be good. Thanks.

**Comment by fredwaltman** [comment]
Hi David,

Didn't feel like doing "real work" this morning so I thought I'd try an
experiment. I downloaded the source of Track Contcatenator from GitHub and
fired it up in Xcode on my iMac running macOS Catalina. I changed all of
the *tell application "iTunes" *to* tell application "Music" *cross my
fingers and hit "Run"

I got a lot of random seeming warnings in the console but when I hit "Get
selected tracks..." they all came up in the text box. I then hit
Concatenate! but nothing happened. I received an error

*2020-08-10 10:48:43.683181-0700 Track Concatenator[39308:67628363] ***
-[DASAppDelegate btnConcatenate:]: 4.302502784E+9 doesn’t understand the
“titleOfSelectedItem” message. (error -1708)*

This was the line

*set mediaTypeText to (radioType's titleOfSelectedItem()) as string*

Not having done any AppleScript in 10+ years (and nothing as complex as
this) I cheated at this point since I am only doing music and replaced the
line with

*set mediaTypeText to "Music track"*

And ran it again and this time it worked perfectly.

The warnings I got at startup were about some items in
/Library/ScriptingAdditions that I guess are real old and XCode complained
they are not SIP Protected. They have nothing to do with your script so I
have no idea why they show up in your app. Mysterious are the ways of
Apple...

The other warning looked more relevant:

*[Nib Loading] Failed to connect (window) outlet from (DASAppDelegate) to
(NSWindow): missing setter or instance variable *

I puzzled over that one for a while. There seemed to be an outlet in the
MainMenu.xib but after doing searching on StackOverflow it appears it is
one of those warnings the XCode sometimes seems to spit out. It didn't seem
to effect execution so I am calling it a win :)

Anyway, I hope this helps.

Cheers,

Fred Waltman

**Comment by davidschlachter** [comment]
Good to hear, thank you for looking into this! I'll integrate all this into the source code and try to get a release out within the next two weeks.

**Comment by davidschlachter** [comment]
I've integrated these changes along with some extra work to keep backwards compatibility with iTunes + ealier macOS versions (tested on Catalina and Mojave). The built-in updater should show the new version (3.0) as available. Thank you again for checking this out!

**Comment by fredwaltman** [comment]
David,

Thanks for this and glad I could help in some small way.

Cheers,

Fred
